services:
  - type: web
    name: kitchen-hub-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: kitchen-hub-db
          property: connectionString

  - type: web
    name: kitchen-hub-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./build
    rootDir: client

databases:
  - name: kitchen-hub-db
    databaseName: kitchen_hub
    user: kitchen_hub_user